insert into user_ratings(name, rating, comment)
values('Aditya',3,'Great quality with great material.')
('Naik',1,'Very Poor')
('Rudra',3,'Very less food.')
('Esha',3,'Okayish!')
('Rupayan',5,'Great quality.')
('Krati',2,'Not upto the mark.')
('Akansha',4,'I loved it.')
('Kalindi',1,'Worst ever product.')